# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Desktop Vault

on:
  push:
  pull_request:
    branches:
      - develop
      - master
      - v4-build-test

jobs:
  desktop-build:
    runs-on: ${{ matrix.system.os }}
    env:
      REACT_APP_NET_TYPE_ID: ${{matrix.network.id}}
      ACTION_OS: ${{ matrix.system.os }}
    strategy:
      matrix:
        system:
          - os: "windows-latest"
            path: "squirrel.windows/x64/"
          - os: "macos-13"
            path: ""
          - os: ubuntu-latest
            path: "deb/x64/"
        network:
          - id: 0
            name: "mainnet"
          - id: 1
            name: "testnet"
          - id: 2
            name: "stagenet"

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install client dependencies
      working-directory: client
      run: |
          git config --global url."https://".insteadOf git://
          npm install

    - name: Audit client dependencies
      working-directory: client
      run: |
          npm audit fix --production

    - name: Client Build for Desktop
      working-directory: client
      env:
        CI: false
      run: |
          npm run build:desktop:ci

    - name: Copy Build
      working-directory: client
      run: |
          npm run copy-build

    - name: Install backend dependencies
      working-directory: haven-desktop-app
      run: |
          npm install

    - name: Install latest wallet core
      working-directory: haven-desktop-app
      run: |
          npm install borgvin/haven-web-core#v4-build-test --save

    - name: Audit backend dependencies
      working-directory: haven-desktop-app
      run: |
          npm audit fix --production

    - if: matrix.system.os == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get install flatpak flatpak-builder elfutils

    - name: Build Final
      run: |
          sh './sh/make.sh'
    - name: Package Desktop Build
      run: |
        cd haven-desktop-app/out/make/${{ matrix.system.path }}
        7z a ${{ github.workspace }}/desktop-${{ matrix.system.os }}-${{ matrix.network.name }}.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: desktop-${{ matrix.system.os }}-${{ matrix.network.name }}.zip
        path: ${{ github.workspace }}/desktop-${{ matrix.system.os }}-${{ matrix.network.name }}.zip
